/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaLoja.view.cadastro;

import SistemaLoja.view.cadastro.cliente.TelaDeCadastroDoCliente;
import SistemaLoja.view.cadastro.distribuidor.TelaDeCadastroDoDistribuidor;
import SistemaLoja.view.cadastro.produto.TelaDeCadastroDoProduto;
import java.awt.ScrollPane;
import javax.swing.JFrame;

/**
 *
 * @author pedroh
 */
public class TelaDeOpcoesDeCadastro extends javax.swing.JFrame {
    
    private TelaDeCadastroDoCliente telaDeCadastroDoCliente;
    private TelaDeCadastroDoDistribuidor telaDeCadastroDoDistribuidor;
    private TelaDeCadastroDoProduto telaDeCadastroDoProduto;

    /**
     * Creates new form TelaDeOpcoesDeCadastro
     */
    public TelaDeOpcoesDeCadastro() {
        initComponents();
        telaDeCadastroDoCliente = new TelaDeCadastroDoCliente();
        scrollPaneClienteCadastro.setViewportView(telaDeCadastroDoCliente);
        telaDeCadastroDoDistribuidor = new TelaDeCadastroDoDistribuidor();
        scrollPaneDistribuidorCadastro.setViewportView(telaDeCadastroDoDistribuidor);
        telaDeCadastroDoProduto = new TelaDeCadastroDoProduto();
        scrollPaneProdutoCadastro.setViewportView(telaDeCadastroDoProduto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPaneCadastro = new javax.swing.JTabbedPane();
        scrollPaneClienteCadastro = new javax.swing.JScrollPane();
        scrollPaneDistribuidorCadastro = new javax.swing.JScrollPane();
        scrollPaneProdutoCadastro = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabPaneCadastro.addTab("Cadastrar cliente", scrollPaneClienteCadastro);
        tabPaneCadastro.addTab("Cadastrar distribuidor", scrollPaneDistribuidorCadastro);
        tabPaneCadastro.addTab("Cadastrar produto", scrollPaneProdutoCadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPaneCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPaneCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeOpcoesDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeOpcoesDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeOpcoesDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeOpcoesDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeOpcoesDeCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPaneClienteCadastro;
    private javax.swing.JScrollPane scrollPaneDistribuidorCadastro;
    private javax.swing.JScrollPane scrollPaneProdutoCadastro;
    private javax.swing.JTabbedPane tabPaneCadastro;
    // End of variables declaration//GEN-END:variables
}
