/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaLoja.view.extras;

import SistemaLoja.view.extras.cliente_sem_email.TelaDeClientesSemEmail;
import SistemaLoja.view.extras.listagem_de_vendas.TelaDeVendas;
import SistemaLoja.view.extras.produtos_vencidos.TelaComProdutosVencidos;
import SistemaLoja.view.extras.total_de_compras.TelaComVendasPorCliente;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author pedroh
 */
public class TelaDeExtras extends javax.swing.JFrame {
    
    private TelaComProdutosVencidos telaComProdutosVencidos;
    private TelaComVendasPorCliente telaComVendasPorCliente;
    private TelaDeClientesSemEmail telaDeClientesSemEmail;
    private TelaDeVendas telaDeVendas;

    /**
     * Creates new form TelaDeExtras
     */
    public TelaDeExtras() {
        initComponents();
        telaComProdutosVencidos = new TelaComProdutosVencidos();
        telaComProdutosVencidos.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        telaComVendasPorCliente = new TelaComVendasPorCliente();
        telaComVendasPorCliente.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        telaDeClientesSemEmail = new TelaDeClientesSemEmail();
        telaDeClientesSemEmail.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        telaDeVendas = new TelaDeVendas();
        telaDeVendas.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProdutosVencidos = new javax.swing.JButton();
        btnClientesSemEmail = new javax.swing.JButton();
        btnVendasEm2020 = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnProdutosVencidos.setText("Listar produtos vencidos");
        btnProdutosVencidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosVencidosActionPerformed(evt);
            }
        });

        btnClientesSemEmail.setText("Listar Clientes sem email");
        btnClientesSemEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesSemEmailActionPerformed(evt);
            }
        });

        btnVendasEm2020.setText("Listar vendas por cliente em 2020");
        btnVendasEm2020.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasEm2020ActionPerformed(evt);
            }
        });

        btnVendas.setText("Listar vendas");
        btnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVendasEm2020, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProdutosVencidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClientesSemEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnClientesSemEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProdutosVencidos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVendasEm2020, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdutosVencidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosVencidosActionPerformed
        // TODO add your handling code here:
        if (!telaComProdutosVencidos.isVisible()) {
            telaComProdutosVencidos.setVisible(true);
        }
    }//GEN-LAST:event_btnProdutosVencidosActionPerformed

    private void btnClientesSemEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesSemEmailActionPerformed
        // TODO add your handling code here:
        if (!telaDeClientesSemEmail.isVisible()) {
            telaDeClientesSemEmail.setVisible(true);
        }
    }//GEN-LAST:event_btnClientesSemEmailActionPerformed

    private void btnVendasEm2020ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasEm2020ActionPerformed
        // TODO add your handling code here:
        if (!telaComVendasPorCliente.isVisible()) {
            telaComVendasPorCliente.setVisible(true);
        }
    }//GEN-LAST:event_btnVendasEm2020ActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed
        // TODO add your handling code here:
        if (!telaDeVendas.isVisible()) {
            telaDeVendas.setVisible(true);
        }        
    }//GEN-LAST:event_btnVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeExtras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientesSemEmail;
    private javax.swing.JButton btnProdutosVencidos;
    private javax.swing.JButton btnVendas;
    private javax.swing.JButton btnVendasEm2020;
    // End of variables declaration//GEN-END:variables
}
