/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaLoja.view.extras.produtos_vencidos;

import SistemaLoja.view.compra.*;
import SistemaLoja.model.produtos.Produto;
import SistemaLoja.model.produtos.ProdutoComprado;
import SistemaLoja.utils.Conversor;

/**
 *
 * @author pedroh
 */
public class CardProdutoVencido extends javax.swing.JPanel {
    
    private Produto produto;

    /**
     * Creates new form ContainerCompraProduto
     */

    public CardProdutoVencido(Produto produto) {
        initComponents();
        setProduto(produto);
        lbNomeDoProduto.setText(produto.getDescricao());
        lbDataValidade.setText(Conversor.dateToString(produto.getDataValidade()));
        lbEstoque.setText(String.valueOf(produto.getEstoque()));
        
    }

    public Produto getProduto() {
        return produto;
    }

    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lbNomeDoProduto = new javax.swing.JLabel();
        lbEstoque = new javax.swing.JLabel();
        lbDataValidade = new javax.swing.JLabel();
        lbEstoqueText = new javax.swing.JLabel();
        lbValidade = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbNomeDoProduto.setText("PRODUTO");

        lbEstoque.setText("0");

        lbDataValidade.setText("VALIDADE");

        lbEstoqueText.setText("Estoque");

        lbValidade.setText("Vencido em");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNomeDoProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                        .addComponent(lbEstoqueText)
                        .addGap(18, 18, 18)
                        .addComponent(lbEstoque)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeDoProduto)
                    .addComponent(lbEstoque)
                    .addComponent(lbEstoqueText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataValidade)
                    .addComponent(lbValidade))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbDataValidade;
    private javax.swing.JLabel lbEstoque;
    private javax.swing.JLabel lbEstoqueText;
    private javax.swing.JLabel lbNomeDoProduto;
    private javax.swing.JLabel lbValidade;
    // End of variables declaration//GEN-END:variables
}
