/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaLoja.view.extras.cliente_sem_email;

import SistemaLoja.model.pessoa_fisica.Cliente;

/**
 *
 * @author pedroh
 */
public class CardCliente extends javax.swing.JPanel {
    
    private Cliente clienteDoContainer;

    public Cliente getClienteDoContainer() {
        return clienteDoContainer;
    }

    public void setClienteDoContainer(Cliente clienteDoContainer) {
        this.clienteDoContainer = clienteDoContainer;
    }    

    public CardCliente(Cliente clienteDoContainer) {
        initComponents();
        setClienteDoContainer(clienteDoContainer);
        conectarLabelsComCliente();
    }
    
    public void conectarLabelsComCliente() {
        lbNome.setText(getClienteDoContainer().getNome());
        lbEmail.setText(getClienteDoContainer().getEmail());
        lbCodigo.setText(String.valueOf(getClienteDoContainer().getIdCliente()));
        
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNomeText = new javax.swing.JLabel();
        lbEmailText = new javax.swing.JLabel();
        lbTelefoneText = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbCodigoText = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        lbEnderecoText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbNumero = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbDescricao = new javax.swing.JLabel();
        lbRuaText = new javax.swing.JLabel();
        lbBairroText = new javax.swing.JLabel();
        lbCidadeText = new javax.swing.JLabel();
        lbRua = new javax.swing.JLabel();
        lbBairro = new javax.swing.JLabel();
        lbCidade = new javax.swing.JLabel();
        lbHifenText = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();

        lbNomeText.setText("Nome");

        lbEmailText.setText("Email");

        lbTelefoneText.setText("Telefone");

        lbNome.setText("NOME");

        lbEmail.setText("EMAIL");

        lbTelefone.setText("TELEFONE");

        lbCodigoText.setText("Código");

        lbCodigo.setText("CODIGO");

        lbEnderecoText.setText("Endereço");

        jLabel1.setText("Número");

        lbNumero.setText("NUMERO");

        jLabel3.setText("Descrição");

        lbDescricao.setText("DESCRICAO");

        lbRuaText.setText("Rua");

        lbBairroText.setText("Bairro");

        lbCidadeText.setText("Cidade");

        lbRua.setText("RUA");

        lbBairro.setText("BAIRRO");

        lbCidade.setText("CIDADE");

        lbHifenText.setText("-");

        lbEstado.setText("ESTADO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTelefoneText)
                            .addComponent(lbEmailText)
                            .addComponent(lbNomeText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNome)
                                    .addComponent(lbTelefone))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                                .addComponent(lbCodigoText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbCodigo)
                                .addGap(30, 30, 30))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEnderecoText)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lbNumero))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(lbRuaText)
                                    .addComponent(lbBairroText)
                                    .addComponent(lbCidadeText))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbCidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbHifenText)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbEstado))
                                    .addComponent(lbBairro)
                                    .addComponent(lbRua)
                                    .addComponent(lbDescricao))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeText)
                    .addComponent(lbNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmailText)
                    .addComponent(lbEmail)
                    .addComponent(lbCodigoText)
                    .addComponent(lbCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefoneText)
                    .addComponent(lbTelefone))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEnderecoText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRuaText)
                    .addComponent(lbRua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBairroText)
                    .addComponent(lbBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCidadeText)
                    .addComponent(lbCidade)
                    .addComponent(lbHifenText)
                    .addComponent(lbEstado))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbBairroText;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbCidadeText;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCodigoText;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEmailText;
    private javax.swing.JLabel lbEnderecoText;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbHifenText;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNomeText;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbRua;
    private javax.swing.JLabel lbRuaText;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JLabel lbTelefoneText;
    // End of variables declaration//GEN-END:variables
}
