/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaLoja.view.compra;

import SistemaLoja.model.produtos.Produto;
import SistemaLoja.model.produtos.ProdutoComprado;

/**
 *
 * @author pedroh
 */
public class ContainerCompraProduto extends javax.swing.JPanel {
    
    private int posicaoProdutoNoContainer;
    private int quantiaEspecificada;
    private ProdutosCompradosAcoes containerPai;
    private Produto produto;

    /**
     * Creates new form ContainerCompraProduto
     */

    public ContainerCompraProduto(int posicaoProdutoNoContainer, ProdutosCompradosAcoes containerPai, Produto produto) {
        initComponents();
        this.posicaoProdutoNoContainer = posicaoProdutoNoContainer;
        this.containerPai = containerPai;
        this.produto = produto;
        lbNomeDoProduto.setText(produto.getDescricao());
        lbDataValidade.setText(produto.getDataValidade().toString());
        lbPreco.setText(String.format("%.2f", produto.getPrecoVenda()));
    }

    public int getPosicaoProdutoNoContainer() {
        return posicaoProdutoNoContainer;
    }

    public void setPosicaoProdutoNoContainer(int posicaoProdutoNoContainer) {
        this.posicaoProdutoNoContainer = posicaoProdutoNoContainer;
    }

    public ProdutosCompradosAcoes getContainerPai() {
        return containerPai;
    }

    public void setContainerPai(ProdutosCompradosAcoes containerPai) {
        this.containerPai = containerPai;
    }

    public Produto getProduto() {
        return produto;
    }

    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lbNomeDoProduto = new javax.swing.JLabel();
        lbQuantia = new javax.swing.JLabel();
        btnDiminuirQuantidade = new javax.swing.JButton();
        btnAumentarQuantidade = new javax.swing.JButton();
        lbDataValidade = new javax.swing.JLabel();
        lbPreco = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbQuantia.setText("0");

        btnDiminuirQuantidade.setText("-");
        btnDiminuirQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiminuirQuantidadeActionPerformed(evt);
            }
        });

        btnAumentarQuantidade.setText("+");
        btnAumentarQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarQuantidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNomeDoProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(115, 115, 115)
                .addComponent(lbPreco)
                .addGap(18, 18, 18)
                .addComponent(btnDiminuirQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbQuantia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAumentarQuantidade)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbPreco))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbNomeDoProduto)
                        .addComponent(lbQuantia)
                        .addComponent(btnAumentarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDiminuirQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(lbDataValidade)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAumentarQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarQuantidadeActionPerformed
        if (quantiaEspecificada < produto.getEstoque()) {
            quantiaEspecificada++;
            lbQuantia.setText(String.valueOf(quantiaEspecificada));
            containerPai.atualizarProdutoComprado(posicaoProdutoNoContainer, new ProdutoComprado(produto, quantiaEspecificada));
        }
    }//GEN-LAST:event_btnAumentarQuantidadeActionPerformed

    private void btnDiminuirQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiminuirQuantidadeActionPerformed
        if (quantiaEspecificada > 0) {
            quantiaEspecificada--;
            lbQuantia.setText(String.valueOf(quantiaEspecificada));            
            containerPai.atualizarProdutoComprado(posicaoProdutoNoContainer, new ProdutoComprado(produto, quantiaEspecificada));
        }
    }//GEN-LAST:event_btnDiminuirQuantidadeActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAumentarQuantidade;
    private javax.swing.JButton btnDiminuirQuantidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbDataValidade;
    private javax.swing.JLabel lbNomeDoProduto;
    private javax.swing.JLabel lbPreco;
    private javax.swing.JLabel lbQuantia;
    // End of variables declaration//GEN-END:variables
}
