/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaLoja.view.extras.listagem_de_vendas;

import SistemaLoja.model.produtos.Venda;
import SistemaLoja.utils.Conversor;

/**
 *
 * @author pedroh
 */
public class CardVenda extends javax.swing.JPanel {
    
    private Venda venda;

    public Venda getVenda() {
        return venda;
    }

    public void setVenda(Venda venda) {
        this.venda = venda;
    }

    public CardVenda(Venda venda) {
        initComponents();
        setVenda(venda);
        ligarVendaComLabels();
        
    }
    
    public void ligarVendaComLabels() {
        lbTotalVenda.setText(String.format("%.2f", getVenda().getTotal()));
        lbDataVenda.setText(Conversor.dateToString(getVenda().getDataHoraVenda()));
        lbCodigo.setText(String.valueOf(getVenda().getIdVenda()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCodigoText = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        lbTotalVendaText = new javax.swing.JLabel();
        lbTotalVenda = new javax.swing.JLabel();
        lbDataVendaText = new javax.swing.JLabel();
        lbDataVenda = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbCodigoText.setText("Código");

        lbCodigo.setText("CODIGO");

        lbTotalVendaText.setText("Total da venda");

        lbTotalVenda.setText("TOTAL");

        lbDataVendaText.setText("Data da venda");

        lbDataVenda.setText("DATA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbCodigoText)
                .addGap(18, 18, 18)
                .addComponent(lbCodigo)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTotalVendaText)
                        .addGap(51, 51, 51)
                        .addComponent(lbTotalVenda))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDataVendaText)
                        .addGap(18, 18, 18)
                        .addComponent(lbDataVenda)))
                .addContainerGap(295, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotalVendaText)
                    .addComponent(lbTotalVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoText)
                    .addComponent(lbCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataVendaText)
                    .addComponent(lbDataVenda))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCodigoText;
    private javax.swing.JLabel lbDataVenda;
    private javax.swing.JLabel lbDataVendaText;
    private javax.swing.JLabel lbTotalVenda;
    private javax.swing.JLabel lbTotalVendaText;
    // End of variables declaration//GEN-END:variables
}
