/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaLoja.view.cadastro.produto;

import SistemaLoja.database.conexao.IBancoDao;
import SistemaLoja.database.conexao.SQLServerDao;
import SistemaLoja.model.produtos.Distribuidor;
import SistemaLoja.model.produtos.Produto;
import SistemaLoja.utils.Conversor;
import SistemaLoja.utils.Mensagem;
import SistemaLoja.utils.Validador;
import java.sql.Date;
import java.util.ArrayList;

/**
 *
 * @author pedroh
 */
public class TelaDeCadastroDoProduto extends javax.swing.JPanel {
    
    private IBancoDao database;
    private Produto produtoCadastrado;
    private ArrayList<Distribuidor> distribuidoresDisponiveis;

    /**
     * Creates new form TelaDeCadastroDoProduto
     */
    public TelaDeCadastroDoProduto() {
        initComponents();
        database = SQLServerDao.getInstance();
        distribuidoresDisponiveis = database.getSelecionarActions().selecionarDistribuidores();
        adicionarDistribuidoresAoComboBox();
    }
    
    private void adicionarDistribuidoresAoComboBox() {
        for (Distribuidor distribuidor: distribuidoresDisponiveis) {
            comboBoxDistribuidor.addItem(distribuidor.getNomeFantasia());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxDistribuidor = new javax.swing.JComboBox<>();
        lbDistribuidorText = new javax.swing.JLabel();
        lbProdutoText = new javax.swing.JLabel();
        lbDescricaoText = new javax.swing.JLabel();
        txtFieldDescricao = new javax.swing.JTextField();
        formatTxtFieldPrecoVenda = new javax.swing.JFormattedTextField();
        lbPrecoVendaText = new javax.swing.JLabel();
        lbPrecoCompraText = new javax.swing.JLabel();
        formatTxtFieldPrecoCompra = new javax.swing.JFormattedTextField();
        formatTxtFieldValidade = new javax.swing.JFormattedTextField();
        lbValidadeText = new javax.swing.JLabel();
        btnConcluirCadastro = new javax.swing.JButton();
        lbObrigatorioValidadeText = new javax.swing.JLabel();
        lbObrigatorioPrecoCompraText = new javax.swing.JLabel();
        lbObrigatorioPrecoVendaText = new javax.swing.JLabel();
        lbObrigatorioDescricaoText = new javax.swing.JLabel();
        lbObrigatorioDistribuidorText = new javax.swing.JLabel();
        lbEstoque = new javax.swing.JLabel();
        formatTxtFieldEstoque = new javax.swing.JFormattedTextField();
        lbObrigatorioEstoqueText1 = new javax.swing.JLabel();

        lbDistribuidorText.setText("Distribuidor");

        lbProdutoText.setText("Produto");

        lbDescricaoText.setText("Descrição");

        txtFieldDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldDescricaoActionPerformed(evt);
            }
        });

        formatTxtFieldPrecoVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        formatTxtFieldPrecoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatTxtFieldPrecoVendaActionPerformed(evt);
            }
        });

        lbPrecoVendaText.setText("Preço venda");

        lbPrecoCompraText.setText("Preço compra");

        formatTxtFieldPrecoCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        formatTxtFieldPrecoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatTxtFieldPrecoCompraActionPerformed(evt);
            }
        });

        formatTxtFieldValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        formatTxtFieldValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatTxtFieldValidadeActionPerformed(evt);
            }
        });

        lbValidadeText.setText("Data de validade");

        btnConcluirCadastro.setText("Concluir cadastro");
        btnConcluirCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirCadastroActionPerformed(evt);
            }
        });

        lbObrigatorioValidadeText.setForeground(new java.awt.Color(255, 51, 51));
        lbObrigatorioValidadeText.setText("Obrigatório");

        lbObrigatorioPrecoCompraText.setForeground(new java.awt.Color(255, 51, 51));
        lbObrigatorioPrecoCompraText.setText("Obrigatório");

        lbObrigatorioPrecoVendaText.setForeground(new java.awt.Color(255, 51, 51));
        lbObrigatorioPrecoVendaText.setText("Obrigatório");

        lbObrigatorioDescricaoText.setForeground(new java.awt.Color(255, 51, 51));
        lbObrigatorioDescricaoText.setText("Obrigatório");

        lbObrigatorioDistribuidorText.setForeground(new java.awt.Color(255, 51, 51));
        lbObrigatorioDistribuidorText.setText("Obrigatório");

        lbEstoque.setText("Estoque");

        formatTxtFieldEstoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lbObrigatorioEstoqueText1.setForeground(new java.awt.Color(255, 51, 51));
        lbObrigatorioEstoqueText1.setText("Obrigatório");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbProdutoText)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbPrecoVendaText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(formatTxtFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPrecoCompraText)
                                    .addComponent(lbValidadeText)
                                    .addComponent(lbEstoque))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(formatTxtFieldValidade)
                                    .addComponent(formatTxtFieldPrecoCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(formatTxtFieldEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbObrigatorioEstoqueText1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbObrigatorioValidadeText)
                            .addComponent(lbObrigatorioPrecoCompraText)
                            .addComponent(lbObrigatorioPrecoVendaText)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDistribuidorText)
                            .addComponent(lbDescricaoText))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxDistribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbObrigatorioDescricaoText)
                            .addComponent(lbObrigatorioDistribuidorText))))
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConcluirCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lbProdutoText)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstoque)
                    .addComponent(formatTxtFieldEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbObrigatorioEstoqueText1))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formatTxtFieldValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbValidadeText)
                    .addComponent(lbObrigatorioValidadeText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecoCompraText)
                    .addComponent(formatTxtFieldPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbObrigatorioPrecoCompraText))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecoVendaText)
                    .addComponent(formatTxtFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbObrigatorioPrecoVendaText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDescricaoText)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDistribuidorText)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboBoxDistribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbObrigatorioDistribuidorText))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbObrigatorioDescricaoText)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btnConcluirCadastro)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private boolean isAlgumCampoObrigatorioVazio() {
        return 
                Validador.isTextoVazio(formatTxtFieldEstoque.getText()) ||
                Validador.isTextoVazio(formatTxtFieldValidade.getText()) ||
                Validador.isTextoVazio(formatTxtFieldPrecoCompra.getText()) ||
                Validador.isTextoVazio(formatTxtFieldPrecoVenda.getText()) ||
                Validador.isTextoVazio(txtFieldDescricao.getText());
    }
    
    private boolean isPrecoMaiorQueZero(float preco) {
        return preco > 0F;
    }
    
    private float converterPrecoFormatFieldParaFloat(String text) {
        return Float.parseFloat(text.replace(',', '.'));
    }
    
    private boolean isPrecosInseridosValidos() {
        float precoCompra = converterPrecoFormatFieldParaFloat(formatTxtFieldPrecoCompra.getText());
        float precoVenda = converterPrecoFormatFieldParaFloat(formatTxtFieldPrecoVenda.getText().replace(',', '.'));
        
        if (!isPrecoMaiorQueZero(precoCompra)) {
            Mensagem.mostrarErro("O valor de preco compra não pode ser menor ou igual a zero");
            return false;
        }
        
        if (!isPrecoMaiorQueZero(precoVenda)) {
            Mensagem.mostrarErro("O valor de preco venda não pode ser menor ou igual a zero");        
            return false;
        }
        
        return true;
    }
    
    private boolean isEstoqueValido() {
        int estoque = Integer.parseInt(formatTxtFieldEstoque.getText());
        
        if (estoque <= 0) {
            Mensagem.mostrarErro("Valor de estoque inválido.");
            return false;
        }
        
        return true;
    }
    
    private boolean isDataValidadeValida() {
        Date dataValidadeInserida = Conversor.StringParaData(formatTxtFieldValidade.getText());
        if(!Validador.isDataDeValidadeValida(dataValidadeInserida)) {
            Mensagem.mostrarErro("Cadastro de produtos vencidos não são permitidos.");
            return false;
        }
        
        return true;
    }
    
    private boolean isDescricaoValida() {
        if (Validador.isNumero(txtFieldDescricao.getText())) {
            Mensagem.mostrarErro("A descrição não pode ser composta por apenas números.");
            return false;
        }
        
        return true;
    }
    
    private boolean isTodosOsCamposObrigatoriosValidos() {
        if (isAlgumCampoObrigatorioVazio()) {
            Mensagem.mostrarErro("Todos os campos com obrigatório devem ser preenchidos.");
            return false;
        }
        
        if (!isPrecosInseridosValidos()) {
            return false;
        }
        
        if (!isEstoqueValido()) {
            return false;
        }
        
        if(!isDataValidadeValida()) {
            return false;
        }
        
        if (!isDescricaoValida()) {
            return false;
        }
        
        return true;
    }
    
    private void cadastrarProduto() {
        Distribuidor d = distribuidoresDisponiveis.get(comboBoxDistribuidor.getSelectedIndex());
        int idDistribuidor = d.getIdDistribuidor();
        
        produtoCadastrado = new Produto(
                0, 
                idDistribuidor, 
                Integer.parseInt(formatTxtFieldEstoque.getText()), 
                Conversor.StringParaData(formatTxtFieldValidade.getText()), 
                txtFieldDescricao.getText(), 
                converterPrecoFormatFieldParaFloat(formatTxtFieldPrecoCompra.getText()), 
                converterPrecoFormatFieldParaFloat(formatTxtFieldPrecoVenda.getText())
        );
        
        boolean isProdutoCadastrado = database.getInserirActions().inserirProduto(produtoCadastrado);
        if (isProdutoCadastrado) {
            Mensagem.mostrarSucesso("Produto cadastrado com sucesso");
        } else {
            Mensagem.mostrarErro("Falha ao cadastrar o produto");
        }
    
    } 
    
    private void formatTxtFieldPrecoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatTxtFieldPrecoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatTxtFieldPrecoVendaActionPerformed

    private void formatTxtFieldPrecoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatTxtFieldPrecoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatTxtFieldPrecoCompraActionPerformed

    private void txtFieldDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldDescricaoActionPerformed

    private void formatTxtFieldValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatTxtFieldValidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatTxtFieldValidadeActionPerformed

    private void btnConcluirCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirCadastroActionPerformed
        // TODO add your handling code here:
        if (isTodosOsCamposObrigatoriosValidos()) {
            cadastrarProduto();
        }
    }//GEN-LAST:event_btnConcluirCadastroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConcluirCadastro;
    private javax.swing.JComboBox<String> comboBoxDistribuidor;
    private javax.swing.JFormattedTextField formatTxtFieldEstoque;
    private javax.swing.JFormattedTextField formatTxtFieldPrecoCompra;
    private javax.swing.JFormattedTextField formatTxtFieldPrecoVenda;
    private javax.swing.JFormattedTextField formatTxtFieldValidade;
    private javax.swing.JLabel lbDescricaoText;
    private javax.swing.JLabel lbDistribuidorText;
    private javax.swing.JLabel lbEstoque;
    private javax.swing.JLabel lbObrigatorioDescricaoText;
    private javax.swing.JLabel lbObrigatorioDistribuidorText;
    private javax.swing.JLabel lbObrigatorioEstoqueText1;
    private javax.swing.JLabel lbObrigatorioPrecoCompraText;
    private javax.swing.JLabel lbObrigatorioPrecoVendaText;
    private javax.swing.JLabel lbObrigatorioValidadeText;
    private javax.swing.JLabel lbPrecoCompraText;
    private javax.swing.JLabel lbPrecoVendaText;
    private javax.swing.JLabel lbProdutoText;
    private javax.swing.JLabel lbValidadeText;
    private javax.swing.JTextField txtFieldDescricao;
    // End of variables declaration//GEN-END:variables
}
