/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaLoja.view.remocao;

import SistemaLoja.model.pessoa_fisica.Cliente;
import SistemaLoja.model.produtos.Distribuidor;
import SistemaLoja.model.produtos.Produto;
import javax.swing.JButton;

/**
 *
 * @author pedroh
 */
public class CardItemComExclusao extends javax.swing.JPanel {
    
    private ExclusaoDeItem exclusaoDeItem;
    private int posicaoDoItem;

    public ExclusaoDeItem getExclusaoDeItem() {
        return exclusaoDeItem;
    }
    
    public void setExclusaoDeItem(ExclusaoDeItem exclusaoDeItem) {
        this.exclusaoDeItem = exclusaoDeItem;
    }

    public int getPosicaoDoItem() {
        return posicaoDoItem;
    }

    public void setPosicaoDoItem(int posicaoDoItem) {
        this.posicaoDoItem = posicaoDoItem;
    }
    
    /**
     * Creates new form CardItemComExclusao
     */
    public CardItemComExclusao() {
        initComponents();
    }

    public CardItemComExclusao(ExclusaoDeItem exclusaoDeItem, int posicaoDoItem) {
        this();
        setExclusaoDeItem(exclusaoDeItem);
        setPosicaoDoItem(posicaoDoItem);
    }

    public CardItemComExclusao(ExclusaoDeItem exclusaoDeItem, int posicaoDoItem, Cliente cliente) {
        this(exclusaoDeItem, posicaoDoItem);
        lbCodigo.setText(String.valueOf(cliente.getIdCliente()));
        lbNome.setText(cliente.getNome());
    }
    
    public CardItemComExclusao(ExclusaoDeItem exclusaoDeItem, int posicaoDoItem, Distribuidor distribuidor) {
        this(exclusaoDeItem, posicaoDoItem);
        lbCodigo.setText(String.valueOf(distribuidor.getIdDistribuidor()));
        lbNome.setText(distribuidor.getNomeFantasia());
    }
    
    public CardItemComExclusao(ExclusaoDeItem exclusaoDeItem, int posicaoDoItem, Produto produto) {
        this(exclusaoDeItem, posicaoDoItem);
        lbCodigo.setText(String.valueOf(produto.getIdProduto()));
        lbNome.setText(produto.getDescricao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCodigoText = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        lbNomeText = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        btnExcluirItem = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbCodigoText.setText("Código");

        lbCodigo.setText("CÓDIGO");

        lbNomeText.setText("Nome");

        lbNome.setText("NOME");

        btnExcluirItem.setText("X");
        btnExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCodigoText)
                    .addComponent(lbNomeText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCodigo)
                    .addComponent(lbNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(btnExcluirItem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoText)
                    .addComponent(lbCodigo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(lbNomeText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnExcluirItem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirItemActionPerformed
        // TODO add your handling code here:
        exclusaoDeItem.excluirItemDePosicao(getPosicaoDoItem());
    }//GEN-LAST:event_btnExcluirItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirItem;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCodigoText;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNomeText;
    // End of variables declaration//GEN-END:variables
}
