/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaLoja.view.cadastro.distribuidor;

import SistemaLoja.database.conexao.IBancoDao;
import SistemaLoja.database.conexao.SQLServerDao;
import SistemaLoja.model.contato.TelefoneDistribuidor;
import SistemaLoja.model.produtos.Distribuidor;
import SistemaLoja.utils.Mensagem;
import SistemaLoja.utils.Validador;
import java.util.ArrayList;

/**
 *
 * @author pedroh
 */
public class TelaDeCadastroDoDistribuidor extends javax.swing.JPanel {
    
    private IBancoDao database;
    private Distribuidor distribuidorCadastrado;
            
    /**
     * Creates new form TelaDeCadastroDoDistribuidor
     */
    public TelaDeCadastroDoDistribuidor() {
        initComponents();
        database = SQLServerDao.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNomeFantasiaText = new javax.swing.JLabel();
        lbRazaoSocialText = new javax.swing.JLabel();
        lbPrimeiroTelefoneText = new javax.swing.JLabel();
        lbSegundoTelefoneText = new javax.swing.JLabel();
        lbEmailText = new javax.swing.JLabel();
        txtFieldNomeFantasia = new javax.swing.JTextField();
        txtFieldRazaoSocial = new javax.swing.JTextField();
        txtFieldEmail = new javax.swing.JTextField();
        btnCadastrarDistribuidor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        formatTxtFieldTelefonePrimeiro = new javax.swing.JFormattedTextField();
        formatTxtFieldTelefoneSegundo = new javax.swing.JFormattedTextField();

        lbNomeFantasiaText.setText("Nome fantasia");

        lbRazaoSocialText.setText("Razão social");

        lbPrimeiroTelefoneText.setText("Telefone(1)");

        lbSegundoTelefoneText.setText("Telefone(2)");

        lbEmailText.setText("Email");

        btnCadastrarDistribuidor.setText("Concluir Cadastro");
        btnCadastrarDistribuidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarDistribuidorActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Obrigatório");

        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Obrigatório");

        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Obrigatório");

        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Obrigatório");

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Obrigatório");

        formatTxtFieldTelefonePrimeiro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        formatTxtFieldTelefoneSegundo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        formatTxtFieldTelefoneSegundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatTxtFieldTelefoneSegundoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lbNomeFantasiaText)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbPrimeiroTelefoneText)
                                .addComponent(lbRazaoSocialText))
                            .addGap(20, 20, 20)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSegundoTelefoneText)
                            .addComponent(lbEmailText))
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFieldRazaoSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtFieldNomeFantasia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFieldEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(formatTxtFieldTelefoneSegundo, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(formatTxtFieldTelefonePrimeiro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrarDistribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeFantasiaText)
                    .addComponent(txtFieldNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbRazaoSocialText)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrimeiroTelefoneText)
                    .addComponent(jLabel3)
                    .addComponent(formatTxtFieldTelefonePrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSegundoTelefoneText)
                    .addComponent(jLabel4)
                    .addComponent(formatTxtFieldTelefoneSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmailText)
                    .addComponent(txtFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(btnCadastrarDistribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private boolean isAlgumCampoObrigatorioVazio() {
        return 
                Validador.isTextoVazio(txtFieldNomeFantasia.getText()) ||
                Validador.isTextoVazio(txtFieldRazaoSocial.getText()) ||
                Validador.isTextoVazio(txtFieldEmail.getText()) ||
                Validador.isTextoVazio(formatTxtFieldTelefonePrimeiro.getText()) ||
                Validador.isTextoVazio(formatTxtFieldTelefoneSegundo.getText());
    }
    
    private boolean isNomeValido(String nome) {
        return !Validador.isNumero(nome);
    }
    
    private boolean isNomeFantasiaValido() {
        return isNomeValido(txtFieldNomeFantasia.getText());
    }
    
    private boolean isRazaoSocialValida() {
        return isNomeValido(txtFieldRazaoSocial.getText());
    }
      
    private boolean isEmailValido() {
        return isNomeValido(txtFieldEmail.getText());
    }
    
    private boolean isPrimeiroTelefoneValido() {
        return Validador.isTelefoneValido(formatTxtFieldTelefonePrimeiro.getText());
    }
    
    private boolean isSegundoTelefoneValido() {
        return Validador.isTelefoneValido(formatTxtFieldTelefoneSegundo.getText());    
    }
    
    private boolean isCamposDeContatoValidos() {
        if (!isEmailValido()) {
            Mensagem.mostrarErro("O email deve conter letras e simbolos ou letras, números e simbolos.");
            
            return false;
        }
        
        if (!isPrimeiroTelefoneValido() || !isSegundoTelefoneValido()) {
            Mensagem.mostrarErro("O telefone deve conter apenas numero e deve ter o tamanho de 8 a 11 caracteres");
            
            return false;
        }
        
        return true;
    }
    
    private boolean isCamposObrigatoriosValidos() {
        if (isAlgumCampoObrigatorioVazio()) {
            Mensagem.mostrarErro("Todos os campos devem ser preenchidos");
            return false;
        }
        
        if (!isNomeFantasiaValido()) {
            Mensagem.mostrarErro("O campo nome fantasia não deve conter apenas numeros.");
            return false;
        
        }
        
        if (!isRazaoSocialValida()) {
            Mensagem.mostrarErro("O campo razão social não deve conter apenas numeros.");
            return false;
        }
        
        if (!isCamposDeContatoValidos()) {
            return false;
        }
        
        return true;
    }
    
    private ArrayList<TelefoneDistribuidor> obterTelefonesDoDistribuidor() {
        ArrayList<TelefoneDistribuidor> telefones = new ArrayList<>();
        telefones.add(new TelefoneDistribuidor(0, 0, formatTxtFieldTelefonePrimeiro.getText()));
        telefones.add(new TelefoneDistribuidor(0, 0, formatTxtFieldTelefoneSegundo.getText()));
        
        return telefones;
    }
    
    private void cadastrarDistribuidor() {
        distribuidorCadastrado = new Distribuidor(
                0,
                txtFieldNomeFantasia.getText(), 
                txtFieldRazaoSocial.getText(), 
                txtFieldEmail.getText(), 
                obterTelefonesDoDistribuidor());
        
        boolean isDistribuidorCadastrado = database.getInserirActions().inserirDistribuidor(distribuidorCadastrado);
        if (isDistribuidorCadastrado) {
            Mensagem.mostrarSucesso("Distribuidor cadastrado com sucesso.");
        } else {
            Mensagem.mostrarSucesso("Erro ao cadastrar o distribuidor.");
        }
    }
    
    private void btnCadastrarDistribuidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarDistribuidorActionPerformed
        // TODO add your handling code here:
        if (isCamposObrigatoriosValidos()) {
            cadastrarDistribuidor();
        }
    }//GEN-LAST:event_btnCadastrarDistribuidorActionPerformed

    private void formatTxtFieldTelefoneSegundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatTxtFieldTelefoneSegundoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatTxtFieldTelefoneSegundoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarDistribuidor;
    private javax.swing.JFormattedTextField formatTxtFieldTelefonePrimeiro;
    private javax.swing.JFormattedTextField formatTxtFieldTelefoneSegundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbEmailText;
    private javax.swing.JLabel lbNomeFantasiaText;
    private javax.swing.JLabel lbPrimeiroTelefoneText;
    private javax.swing.JLabel lbRazaoSocialText;
    private javax.swing.JLabel lbSegundoTelefoneText;
    private javax.swing.JTextField txtFieldEmail;
    private javax.swing.JTextField txtFieldNomeFantasia;
    private javax.swing.JTextField txtFieldRazaoSocial;
    // End of variables declaration//GEN-END:variables
}
