/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaLoja.view.remocao.cliente;

import SistemaLoja.view.remocao.ExclusaoDeItem;
import SistemaLoja.database.conexao.IBancoDao;
import SistemaLoja.database.conexao.SQLServerDao;
import SistemaLoja.model.pessoa_fisica.Cliente;
import SistemaLoja.utils.Mensagem;
import SistemaLoja.view.remocao.CardItemComExclusao;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author pedroh
 */
public class TelaDeExclusaoDeClientes extends javax.swing.JPanel implements ExclusaoDeItem {
    
    private IBancoDao database;
    private ArrayList<Cliente> clientesDisponiveis;
    private ArrayList<CardItemComExclusao> clientesCards;
    private JPanel cardsContainer;

    /**
     * Creates new form TelaDeExclusaoDeClientes
     */
    public TelaDeExclusaoDeClientes() {
        initComponents();
        database = SQLServerDao.getInstance();
        cardsContainer = new JPanel();
        cardsContainer.setLayout(new BoxLayout(cardsContainer, BoxLayout.Y_AXIS));
        scrollPaneCliente.setViewportView(cardsContainer);
    }
    
    private void popularClientes() {
        cardsContainer.removeAll();
        if (clientesDisponiveis.size() < 1) {
            Mensagem.mostrarErro("Não existem clientes cadastrados no banco");
        }
        
        for (int pos=0; pos < clientesDisponiveis.size(); pos++) {
            cardsContainer.add(new CardItemComExclusao(this, pos, clientesDisponiveis.get(pos)));
        }
        cardsContainer.updateUI();
    
    }

    @Override
    public void excluirItemDePosicao(int pos) {
        Cliente clienteSelecionado = clientesDisponiveis.get(pos);
        boolean isClienteRemovido = database.getRemoverActions().removerCliente(clienteSelecionado);
        if (isClienteRemovido) {
            Mensagem.mostrarSucesso("Cliente removido");
        } else {
            Mensagem.mostrarSucesso("Falha ao remover o cliente");
        }
        clientesDisponiveis = database.getSelecionarActions().selecionarClientes();
        popularClientes();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneCliente = new javax.swing.JScrollPane();
        btnAtualizar = new javax.swing.JButton();

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneCliente)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(455, Short.MAX_VALUE)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(scrollPaneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        clientesDisponiveis = database.getSelecionarActions().selecionarClientes();
        popularClientes();
    }//GEN-LAST:event_btnAtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JScrollPane scrollPaneCliente;
    // End of variables declaration//GEN-END:variables

}
