/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaLoja.view.remocao.produto;

import SistemaLoja.view.remocao.ExclusaoDeItem;
import SistemaLoja.view.remocao.cliente.*;
import SistemaLoja.database.conexao.IBancoDao;
import SistemaLoja.database.conexao.SQLServerDao;
import SistemaLoja.model.pessoa_fisica.Cliente;
import SistemaLoja.model.produtos.Produto;
import SistemaLoja.utils.Mensagem;
import SistemaLoja.view.remocao.CardItemComExclusao;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author pedroh
 */
public class TelaDeExclusaoDeProdutos extends javax.swing.JPanel implements ExclusaoDeItem {
    
    private IBancoDao database;
    private ArrayList<Produto> produtoDisponiveis;
    private ArrayList<CardItemComExclusao> produtoCards;
    private JPanel cardsContainer;

    /**
     * Creates new form TelaDeExclusaoDeClientes
     */
    public TelaDeExclusaoDeProdutos() {
        initComponents();
        database = SQLServerDao.getInstance();
        cardsContainer = new JPanel();
        cardsContainer.setLayout(new BoxLayout(cardsContainer, BoxLayout.Y_AXIS));
        scrollPaneProdutos.setViewportView(cardsContainer);

    }
  
    private void popularProdutos() {
        cardsContainer.removeAll();
        if (produtoDisponiveis.size() < 1) {
            Mensagem.mostrarErro("Não existem produtos cadastrados no banco");
        }
       
        for (int pos=0; pos < produtoDisponiveis.size(); pos++) {
            cardsContainer.add(new CardItemComExclusao(this, pos, produtoDisponiveis.get(pos)));
        }
        
        cardsContainer.updateUI();
    }

    @Override
    public void excluirItemDePosicao(int pos) {
        Produto produtoSelecionado = produtoDisponiveis.get(pos);
        boolean isProdutoRemovido = database.getRemoverActions().removerProduto(produtoSelecionado);
        if (isProdutoRemovido) {
            Mensagem.mostrarSucesso("Produto removido");
        } else {
            Mensagem.mostrarErro("Falha ao remover o produto");
        }
        produtoDisponiveis = database.getSelecionarActions().selecionarProdutos();
        popularProdutos();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneProdutos = new javax.swing.JScrollPane();
        btnAtualizar = new javax.swing.JButton();

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneProdutos)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(449, Short.MAX_VALUE)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addComponent(btnAtualizar)
                .addGap(63, 63, 63)
                .addComponent(scrollPaneProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        produtoDisponiveis = database.getSelecionarActions().selecionarProdutos();
        popularProdutos();
    }//GEN-LAST:event_btnAtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JScrollPane scrollPaneProdutos;
    // End of variables declaration//GEN-END:variables

}
